export default {
  ON_VIEWER_INIT_COMPLETED: 'ON_VIEWER_INIT_COMPLETED_asdjflf',
  ON_SWITCH_MAIN3D: 'ON_SWITCH_MAIN3D_432qry',
  ON_SWITCH_MAIN2D: 'ON_SWITCH_MAIN2D_342rto',
  ON_SWITCH_ONLY3D: 'ON_SWITCH_ONLY3D_njmkaf',
  ON_SWITCH_BOTH: 'ON_SWITCH_BOTH_2u8ojiwaf',
  ON_FULL_SCREEN: 'ON_FULL_SCREEN_dasdkahsd',
  ON_CLOSE_SCREEN: 'ON_CLOSE_SCREEN_daksjdka',
  ON_HANDLE_LAYER: 'ON_HANDLE_LAYER_dkajhsakhd',
};
