export const CHANGE_MODE = "CHANGE_MODE";
export const UPDATE_LIST = "UPDATE_LIST";
export const MOVE_POINTER = "MOVE_POINTER";
export const RESET_HISTORY = "RESET_HISTORY";
export const CHANGE_MOUSE_ICON = "CHANGE_MOUSE_ICON";
// 构件信息是否显示
export const COMPONENT_INFO_VISIBLE = "COMPONENT_INFO_VISIBLE";
// 部件族信息显示
export const FAMILY_INFO_VISIBLE = "FAMILY_INFO_VISIBLE";
